# Generated by Django 5.1.2 on 2025-11-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('correo_contacto', models.EmailField(default='contacto@empresa.com', max_length=254, unique=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cedula_juridica', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(default='temp123', max_length=255)),
            ],
        ),
    ]
